# Notes and assumptions
# - load COVID incidence curves from WHO dashboard
# - estimate reproduction numbers with EpiFilter 

# Clean the workspace and console
closeAllConnections(); rm(list=ls())
cat("\014"); graphics.off()

# Set working directory to source
setwd("/Users/rhysinward/Documents/Master's_paper/EpiFilter")

# Folder path for results
folres = paste0("./results/covid/")

# Main functions to run EpiFilter
files.sources = list.files(path = "./main")
for (i in 1:length(files.sources)) {
  source(paste0(c("./main/", files.sources[i]), collapse = ''))
}
# Load data from WHO for New Zealand
alldata = read.csv('Hong_Kong-COVID-19-data.csv')
idcountry = which(alldata$Country == 'Hong Kong')

# Incidence and dates
Iday = alldata$New_cases[idcountry]
dates  = alldata$Date_reported[idcountry]
# Time series lengths
nday = length(dates); tday = 1:nday

# Approximate serial interval distribution from Ferguson et al
wdist = dgamma(tday, shape = 2.3669, scale = 2.7463)

# Total infectiousness
Lday = rep(0, nday) 
for(i in 2:nday){
  # Total infectiousness
  Lday[i] = sum(Iday[seq(i-1, 1, -1)]*wdist[1:(i-1)])    
}

######################################################################
## EpiFilter: provides formally smoothed and exact estimates
# Method based on Bayesian recursive filtering and smoothing
######################################################################

# Setup grid and noise parameters
Rmin = 0.01; Rmax = 10; eta = 0.1

# Uniform prior over grid of size m
m = 200; pR0 = (1/m)*rep(1, m)
# Delimited grid defining space of R
Rgrid = seq(Rmin, Rmax, length.out = m)

# Filtered (causal) estimates as list [Rmed, Rhatci, Rmean, pR, pRup, pstate]
Rfilt = epiFilter(Rgrid, m, eta, pR0, nday, Lday[tday], Iday[tday], 0.025)
# Causal predictions from filtered estimates [pred predci]
Ifilt = recursPredict(Rgrid, Rfilt[[4]], Lday[tday], Rfilt[[3]], 0.025)
#have an extra argument for twice maximum of incidence 
# Smoothed estimates as list of [Rmed, Rhatci, Rmean, qR]
Rsmooth = epiSmoother(Rgrid, m, Rfilt[[4]], Rfilt[[5]], nday, Rfilt[[6]], 0.025)
# Smoothed predictions from filtered estimates [pred predci]
Ismooth = recursPredict(Rgrid, Rsmooth[[4]], Lday[tday], Rsmooth[[3]], 0.025)

#plot rsmooth to see what it looks like (need to do for each time point)

plot(Rgrid, Rsmooth[[4]][1,])

#making sure it adds to one

sum( Rsmooth[[4]][1,])
length(Rsmooth[[4]][1,])

#Load packages

library(tidyverse)
library(safejoin)
library(data.table)
library(lubridate)
library(dplyr)
library(zoo) 
library(countrycode) 
library(purrr) 
library(readr) 
library(stringr)   
library(tidyr) 
library(usdata)
library(seqinr)
library(ggplot2)
library(xts)
library(grid)

# Set working directory 
setwd("/Users/rhysinward/Documents/Master's_paper/Data/Jennsen_Shannon_divergence/Hong_Kong/BDSKY")


#upload PDF generated by tracer 
##unsampled##

#time 1

data <- read.csv ('Unsampled/unsampled_rt1..txt',sep='')
plot(data$unsampled_new_Sampling.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

pdf2cdf <- function(p, x=NULL, normalize=TRUE, expand=FALSE){
  if(is.null(x)) {
    if(is.atomic(p)){
      y <- p
      x <- seq(length(y))
    } else {
      stopifnot(exists("x", where=p) && exists("y", where=p))
      y <- p$y
      x <- p$x
    }
  } else {
    stopifnot(is.atomic(p) && is.atomic(x))
    y <- p
  }
  
  stopifnot(length(x)==length(y))
  stopifnot(length(x) > 2)
  stopifnot(all(is.finite(x)))
  stopifnot(all(is.finite(y)))
  stopifnot(all(diff(x) > 0))
  
  if(any(y < 0)){
    y[y < 0] <- 0
  }
  
  ## trapezoids: N = no., L = left height, R = right height, W = width
  N <- length(y) + 1
  L <- c(0,y)
  R <- c(y,0)
  W <- diff(x)
  W <- c(W[1], W, W[N-2])
  area <- W * (L + R) / 2
  cdf <- cumsum(area)
  
  if(normalize){
    cdf <- cdf / cdf[N]
  }
  if(expand){
    return(list(x=c(x[1]-W[1],x,x[N-1]+W[N]), y=c(0,cdf)))
  } else {
    return(list(x=x, y=cdf[-N]))
  }
}

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$unsampled_new_Sampling.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

d <- seq(from = 0.025, to = 6.725, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:66

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][1,])


inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('unsampled_rt2..txt',sep='')
plot(data$unsampled_new_Sampling.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$unsampled_new_Sampling.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_new_Sampling.log)
d <- seq(from = 0.025, to = 6.425, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:72

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][18,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt2

#time point 3

data <- read.csv ('unsampled_rt3..txt',sep='')
plot(data$unsampled_new_Sampling.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$unsampled_new_Sampling.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_new_Sampling.log)
d <- seq(from = 0.025, to = 3.075, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:139

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][35,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][35,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt3

#time point 4

data <- read.csv ('unsampled_rt4..txt',sep='')
plot(data$unsampled_new_Sampling.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$unsampled_new_Sampling.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_new_Sampling.log)
d <- seq(from = 0.025, to = 3.375, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:133

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][51,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][51,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt4

data <- read.csv ('unsampled_rt5..txt',sep='')
plot(data$unsampled_new_Sampling.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$unsampled_new_Sampling.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_new_Sampling.log)
d <- seq(from = 0.025, to = 1.925, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:162

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][68,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][68,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt5

JS_unsampled <- sum(JS_unsampled_rt1,JS_unsampled_rt2,JS_unsampled_rt3,JS_unsampled_rt4,JS_unsampled_rt5)/5
JS_unsampled

##uniform##

#time 1

data <- read.csv ('uniform_rt1.txt',sep='')
plot(data$uniform_sampling_alligned_ORF1AB_removed.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$uniform_sampling_alligned_ORF1AB_removed.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$uniform_sampling_alligned_ORF1AB_removed.log)

d <- seq(from = 0.025, to = 8.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:40

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)
plot(Rgrid, Rsmooth[[4]][1,])
inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('uniform_rt2.txt',sep='')
plot(data$uniform_sampling_alligned_ORF1AB_removed.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$uniform_sampling_alligned_ORF1AB_removed.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_sampling_alligned_ORF1AB_removed.log)
d <- seq(from = 0.025, to = 4.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:120

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][18,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt2

#time point 3

data <- read.csv ('uniform_rt3.txt',sep='')
plot(data$uniform_sampling_alligned_ORF1AB_removed.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$uniform_sampling_alligned_ORF1AB_removed.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_sampling_alligned_ORF1AB_removed.log)
d <- seq(from = 0.075, to = 4.175, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:118

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][35,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][35,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt3

#time point 4

data <- read.csv ('uniform_rt4.txt',sep='')
plot(data$uniform_sampling_alligned_ORF1AB_removed.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$uniform_sampling_alligned_ORF1AB_removed.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_sampling_alligned_ORF1AB_removed.log)
d <- seq(from = 0.175, to = 2.825, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:147

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][51,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][51,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt4

data <- read.csv ('uniform_rt5.txt',sep='')
plot(data$uniform_sampling_alligned_ORF1AB_removed.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$uniform_sampling_alligned_ORF1AB_removed.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_sampling_alligned_ORF1AB_removed.log)
d <- seq(from = 0.075, to = 2.625, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:149

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][68,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][68,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt5

JS_uniform <- sum(JS_uniform_rt1,JS_uniform_rt2,JS_uniform_rt3,JS_uniform_rt4,JS_uniform_rt5)/5
JS_uniform

#proportional 

#time 1

data <- read.csv ('proportional_rt1.txt',sep='')
plot(data$Hong_Kong_case_sample_alligned_ORF1AB.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$Hong_Kong_case_sample_alligned_ORF1AB.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$Hong_Kong_case_sample_alligned_ORF1AB.log)

d <- seq(from = 0.025, to = 7.75, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:46

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('proportional_rt2.txt',sep='')
plot(data$Hong_Kong_case_sample_alligned_ORF1AB.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$Hong_Kong_case_sample_alligned_ORF1AB.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$Hong_Kong_case_sample_alligned_ORF1AB.log)
d <- seq(from = 0.025, to = 4.975, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:101

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][18,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt2

#time point 3

data <- read.csv ('proportional_rt3.txt',sep='')
plot(data$Hong_Kong_case_sample_alligned_ORF1AB.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$Hong_Kong_case_sample_alligned_ORF1AB.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$Hong_Kong_case_sample_alligned_ORF1AB.log)
d <- seq(from = 0.075, to = 3.575, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:130

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][35,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][35,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt3

#time point 4

data <- read.csv ('proportional_rt4.txt',sep='')
plot(data$Hong_Kong_case_sample_alligned_ORF1AB.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$Hong_Kong_case_sample_alligned_ORF1AB.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$Hong_Kong_case_sample_alligned_ORF1AB.log)
d <- seq(from = 0.125, to = 4.725, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:108

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][51,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][51,])

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt4

data <- read.csv ('proportional_rt5.txt',sep='')
plot(data$Hong_Kong_case_sample_alligned_ORF1AB.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$Hong_Kong_case_sample_alligned_ORF1AB.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$Hong_Kong_case_sample_alligned_ORF1AB.log)
d <- seq(from = 0.025, to = 2.125, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:158

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][68,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][68,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt5

JS_proportional <- sum(JS_proportional_rt1,JS_proportional_rt2,JS_proportional_rt3,JS_proportional_rt4,JS_proportional_rt5)/5
JS_proportional

#inverse

#time 1

data <- read.csv ('inverse_rt1.txt',sep='')
plot(data$inverse_proportion_Hong_Kong.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$inverse_proportion_Hong_Kong.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$inverse_proportion_Hong_Kong.log)

d <- seq(from = 0.025, to = 6.725, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:66

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, Rsmooth[[4]][1,])

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('inverse_rt2.txt',sep='')
plot(data$inverse_proportion_Hong_Kong.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$inverse_proportion_Hong_Kong.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_proportion_Hong_Kong.log)
d <- seq(from = 0.1325, to = 5.775, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:88

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][18,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt2

#time point 3

data <- read.csv ('inverse_rt3.txt',sep='')
plot(data$inverse_proportion_Hong_Kong.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$inverse_proportion_Hong_Kong.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_proportion_Hong_Kong.log)
d <- seq(from = 0.025, to = 3.475, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:131

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][35,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][35,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt3

#time point 4

data <- read.csv ('inverse_rt4.txt',sep='')
plot(data$inverse_proportion_Hong_Kong.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$inverse_proportion_Hong_Kong.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_proportion_Hong_Kong.log)
d <- seq(from = 0.125, to = 2.25, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:158

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][51,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][51,])

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt4

data <- read.csv ('inverse_rt5.txt',sep='')
plot(data$inverse_proportion_Hong_Kong.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$inverse_proportion_Hong_Kong.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_proportion_Hong_Kong.log)
d <- seq(from = 0.075, to = 2.525, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:151

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][68,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][68,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt5

JS_inverse <- sum(JS_inverse_rt1,JS_inverse_rt2,JS_inverse_rt3,JS_inverse_rt4,JS_inverse_rt5)/5
JS_inverse

JS_proportional
JS_inverse
JS_uniform
JS_unsampled
