######################################################################
## Apply EpiFilter to COVID data from New Zealand
# From: Parag, KV, (2020) "Improved real-time estimation of reproduction numbers
# at low case incidence and between epidemic waves" BioRxiv.
######################################################################

# Notes and assumptions
# - load COVID incidence curves from WHO dashboard
# - estimate reproduction numbers with EpiFilter 

# Clean the workspace and console
closeAllConnections(); rm(list=ls())
cat("\014"); graphics.off()

# Set working directory to source
this.dir <- dirname(parent.frame(2)$ofile)
setwd(this.dir)
# Folder path for results
folres = paste0("./results/covid/")

# Main functions to run EpiFilter
files.sources = list.files(path = "./main")
for (i in 1:length(files.sources)) {
  source(paste0(c("./main/", files.sources[i]), collapse = ''))
}
# Load data from WHO for New Zealand
alldata = read.csv('Brazil-COVID-19-data_updated.csv')
idcountry = which(alldata$Country == 'Brazil')

# Incidence and dates
Iday = alldata$New_cases[idcountry]
dates  = alldata$Date_reported[idcountry]
# Time series lengths
nday = length(dates); tday = 1:nday

# Approximate serial interval distribution from Ferguson et al
wdist = dgamma(tday, shape = 2.3669, scale = 2.7463)

# Total infectiousness
Lday = rep(0, nday) 
for(i in 2:nday){
  # Total infectiousness
  Lday[i] = sum(Iday[seq(i-1, 1, -1)]*wdist[1:(i-1)])    
}

######################################################################
## EpiFilter: provides formally smoothed and exact estimates
# Method based on Bayesian recursive filtering and smoothing
######################################################################

# Setup grid and noise parameters
Rmin = 0.01; Rmax = 10; eta = 0.1

# Uniform prior over grid of size m
m = 200; pR0 = (1/m)*rep(1, m)
# Delimited grid defining space of R
Rgrid = seq(Rmin, Rmax, length.out = m)

# Filtered (causal) estimates as list [Rmed, Rhatci, Rmean, pR, pRup, pstate]
Rfilt = epiFilter(Rgrid, m, eta, pR0, nday, Lday[tday], Iday[tday], 0.025)
# Causal predictions from filtered estimates [pred predci]

recursPredict1 <- function(Rgrid, pR, Lday, Rmean, a){
  
  # Grid size and length of time series
  nday = nrow(pR); m = ncol(pR)
  # Test lengths of inputs
  if (length(Rgrid) != m | length(Lday) != nday){
    stop("Input vectors of incorrect dimension")
  }
  
  # Mean prediction: Lday[i] => Iday[i+1]
  pred = Lday*Rmean; pred = pred[1:length(pred)-1]
  
  # Discrete space of possible predictions
  Igrid = 0:50000; lenI = length(Igrid);
  
  # Check if close to upper bound
  if (any(pred > 0.9*max(Igrid))){
    stop("Epidemic size too large")  
  }
  
  # Prediction cdf and quantiles (50% and 95%)
  Fpred = matrix(0, nday-1, lenI)
  predInt = matrix(0, 4, nday-1)
  
  # At every time construct CDF of predictions
  for(i in 1:(nday-1)){
    # Compute rate from Poisson renewal
    rate = Lday[i]*Rgrid
    # Prob of any I marginalised over Rgrid
    pI = rep(0, lenI)
    
    # Probabilities of observations 1 day ahead
    for(j in 1:lenI){
      # Raw probabilities of Igrid
      pIset = dpois(Igrid[j], rate)
      # Normalised by probs of R
      pI[j] = sum(pIset*pR[i, ])
    }
    
    # Quantile predictions and CDF at i+1
    Fpred[i, ] = cumsum(pI)/sum(pI)
    id1 = which(Fpred[i, ] >= a); id2 = which(Fpred[i, ] >= 1-a)
    id3 = which(Fpred[i, ] >= 0.25); id4 = which(Fpred[i, ] >= 0.75)
    
    # Assign prediction results
    predInt[1, i] = Igrid[id1[1]]; predInt[2, i] = Igrid[id2[1]]
    predInt[3, i] = Igrid[id3[1]]; predInt[4, i] = Igrid[id4[1]]
  }
  # Main outputs: mean and 95% predictions
  recursPredict = list(pred, predInt)
}
Ifilt = recursPredict1(Rgrid, Rfilt[[4]], Lday[tday], Rfilt[[3]], 0.025)

#have an extra argument for twice maximum of incidence 
# Smoothed estimates as list of [Rmed, Rhatci, Rmean, qR]
Rsmooth = epiSmoother(Rgrid, m, Rfilt[[4]], Rfilt[[5]], nday, Rfilt[[6]], 0.025)
# Smoothed predictions from filtered estimates [pred predci]
Ismooth = recursPredict1(Rgrid, Rsmooth[[4]], Lday[tday], Rsmooth[[3]], 0.025)


#plot rsmooth to see what it looks like (need to do for each time point)

plot(Rgrid, Rsmooth[[4]][1,])

#making sure it adds to one

sum( Rsmooth[[4]][1,])
length(Rsmooth[[4]][1,])
#upload PDF generated by tracer 
##unsampled##

#time 1

data <- read.csv ('unsampled_rt1.txt',sep='')
plot(data$unsampled_Brazil.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

pdf2cdf <- function(p, x=NULL, normalize=TRUE, expand=FALSE){
  if(is.null(x)) {
    if(is.atomic(p)){
      y <- p
      x <- seq(length(y))
    } else {
      stopifnot(exists("x", where=p) && exists("y", where=p))
      y <- p$y
      x <- p$x
    }
  } else {
    stopifnot(is.atomic(p) && is.atomic(x))
    y <- p
  }
  
  stopifnot(length(x)==length(y))
  stopifnot(length(x) > 2)
  stopifnot(all(is.finite(x)))
  stopifnot(all(is.finite(y)))
  stopifnot(all(diff(x) > 0))
  
  if(any(y < 0)){
    y[y < 0] <- 0
  }
  
  ## trapezoids: N = no., L = left height, R = right height, W = width
  N <- length(y) + 1
  L <- c(0,y)
  R <- c(y,0)
  W <- diff(x)
  W <- c(W[1], W, W[N-2])
  area <- W * (L + R) / 2
  cdf <- cumsum(area)
  
  if(normalize){
    cdf <- cdf / cdf[N]
  }
  if(expand){
    return(list(x=c(x[1]-W[1],x,x[N-1]+W[N]), y=c(0,cdf)))
  } else {
    return(list(x=x, y=cdf[-N]))
  }
}

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$unsampled_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$unsampled_Brazil.log)

d <- seq(from = 0.025, to = 6.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:80

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][1,])

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('unsampled_rt2.txt',sep='')
plot(data$unsampled_Brazil.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$unsampled_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_Brazil.log)
d <- seq(from = 0.025, to = 5.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:100

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][15,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt2

#time point 3

data <- read.csv ('unsampled_rt3.txt',sep='')
plot(data$unsampled_Brazil.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$unsampled_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_Brazil.log)
d <- seq(from = 0.025, to = 5.575, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:89

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][29,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][29,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt3

#time point 4

data <- read.csv ('unsampled_rt4.txt',sep='')
plot(data$unsampled_Brazil.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$unsampled_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_Brazil.log)
d <- seq(from = 0.275, to = 4.775, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:110

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][43,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][43,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt4

data <- read.csv ('unsampled_rt5.txt',sep='')
plot(data$unsampled_Brazil.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$unsampled_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$unsampled_Brazil.log)
d <- seq(from = 0.175, to = 1.41, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:176

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][57,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][57,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_unsampled_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_unsampled_rt5

JS_unsampled <- sum(JS_unsampled_rt1,JS_unsampled_rt2,JS_unsampled_rt3,JS_unsampled_rt4,JS_unsampled_rt5)/5
JS_unsampled

##uniform##

#time 1

data <- read.csv ('uniform_rt1.txt',sep='')
plot(data$uniform_Brazil.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$uniform_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$ uniform_Brazil.log)

d <- seq(from = 0.025, to = 10.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

#add <- 1:83

#add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('uniform_rt2.txt',sep='')
plot(data$uniform_Brazil.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$uniform_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_Brazil.log)
d <- seq(from = 0.025, to = 8.225, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:36

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][15,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt2

#time point 3

data <- read.csv ('uniform_rt3.txt',sep='')
plot(data$uniform_Brazil.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$uniform_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_Brazil.log)
d <- seq(from = 0.025, to = 6.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:80

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][29,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][29,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt3

#time point 4

data <- read.csv ('uniform_rt4.txt',sep='')
plot(data$uniform_Brazil.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$uniform_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_Brazil.log)
d <- seq(from = 0.125, to = 3.625, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:130

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][43,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][43,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt4

data <- read.csv ('uniform_rt5.txt',sep='')
plot(data$uniform_Brazil.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$uniform_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$uniform_Brazil.log)
d <- seq(from = 0.125, to = 1.775, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:167

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][57,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][57,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_uniform_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_uniform_rt5

JS_uniform <- sum(JS_uniform_rt1,JS_uniform_rt2,JS_uniform_rt3,JS_uniform_rt4,JS_uniform_rt5)/5
JS_uniform

#proportional 

#time 1

data <- read.csv ('proportional_rt1.txt',sep='')
plot(data$beast,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$beast, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$beast)

d <- seq(from = 0.025, to = 10.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:103

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('proportional_rt2.txt',sep='')
plot(data$beast,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$beast, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$beast)
d <- seq(from = 0.025, to = 9.775, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:5

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][15,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt2

#time point 3

data <- read.csv ('proportional_rt3.txt',sep='')
plot(data$beast,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$beast, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$beast)
d <- seq(from = 0.025, to = 6.075, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:79

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][29,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][29,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt3

#time point 4

data <- read.csv ('proportional_rt4.txt',sep='')
plot(data$beast,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$beast, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$beast)
d <- seq(from = 0.075, to = 3.775, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:126

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][43,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][43,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt4

data <- read.csv ('proportional_rt5.txt',sep='')
plot(data$beast,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$beast, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$beast)
d <- seq(from = 0.125, to = 1.875, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:165

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][57,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][57,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_proportional_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_proportional_rt5

JS_proportional <- sum(JS_proportional_rt1,JS_proportional_rt2,JS_proportional_rt3,JS_proportional_rt4,JS_proportional_rt5)/5
JS_proportional

#inverse

#time 1

data <- read.csv ('inverse_rt1.txt',sep='')
plot(data$inverse_Brazil.log,data$reproductiveNumber_BDSKY_Serial.1)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.1, x = data$inverse_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.


#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number

summary(data$inverse_Brazil.log)

d <- seq(from = 0.025, to = 10.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

#add <- 1:66

#add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- frequency

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt1 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt1
#need to repeat for each time point 

#time point 2

data <- read.csv ('inverse_rt2.txt',sep='')
plot(data$inverse_Brazil.log,data$reproductiveNumber_BDSKY_Serial.3)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.3, x = data$inverse_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_Brazil.log)
d <- seq(from = 0.025, to = 10.025, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

#add <- 1:88

#add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- frequency

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

inMatrix <- rbind(combined$a,Rsmooth[[4]][18,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt2 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt2

#time point 3

data <- read.csv ('inverse_rt3.txt',sep='')
plot(data$inverse_Brazil.log,data$reproductiveNumber_BDSKY_Serial.5)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.5, x = data$inverse_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_Brazil.log)
d <- seq(from = 0.025, to = 7.625, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:48

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][35,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][35,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt3 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt3

#time point 4

data <- read.csv ('inverse_rt4.txt',sep='')
plot(data$inverse_Brazil.log,data$reproductiveNumber_BDSKY_Serial.7)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.7, x = data$inverse_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_Brazil.log)
d <- seq(from = 0.125, to = 3.375, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:135

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][51,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][51,])

inMatrix <- rbind(combined$a,Rsmooth[[4]][1,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt4 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt4

data <- read.csv ('inverse_rt5.txt',sep='')
plot(data$inverse_Brazil.log,data$reproductiveNumber_BDSKY_Serial.9)

#convert the PDF to a CDF 

cdf <- pdf2cdf(data$reproductiveNumber_BDSKY_Serial.9, x = data$inverse_Brazil.log, normalize = TRUE, expand = FALSE)
cdf <- as.data.frame(cdf)
plot(cdf)

#code the cumulative probability of 0.025, 0.075 - 0.025 ect
#sum of probabilities cloest to 0.
#starting at 0.025, input values at 0.075 intervals 
#so need to select values from 0.025 and at each 0.05 interval from there and then subtract to get grid 200 and that is the PMF
which(abs(cdf$x-1)==min(abs(cdf$x-1)))

d <- as.numeric(cdf$x)

library(data.table)

a=data.table(Value=cdf$x)

a[,merge:=Value]

#want to start at 0.025 and increase in intervals of 0.05 and you want to get the values closest to this number
summary(data$inverse_Brazil.log)
d <- seq(from = 0.175, to = 2.825, by = 0.05)

b=data.table(Value=d)

b[,merge:=Value]

setkeyv(a,c('merge'))

setkeyv(b,c('merge'))

Merge_a_b=a[b,roll='nearest']

Merge_a_b

val <- as.data.frame(Merge_a_b)

library(dplyr)

#get only the values that correspond to the nearest associated value 

culm <- cdf %>% filter(x %in% val$Value)

culm_grid <- cbind(culm, d)

frequency <- as.data.frame(c(diff(culm_grid$y)))

#check to see if it adds to 1

sum(frequency)

#make sure the column lengths allign

add <- 1:147

add <- as.data.frame(replace(add, add>0, 0))

colnames(frequency)[1] <- "a"
colnames(add)[1] <- "a"

combined <- rbind(frequency,add)

#need to create a maxtrix

combined <- transform(combined, a = as.numeric(a))

plot(Rgrid, combined$a)

plot(Rgrid, Rsmooth[[4]][68,] )

inMatrix <- rbind(combined$a,Rsmooth[[4]][68,])

colnames(inMatrix)  <- c(1:200)

rownames(inMatrix) <- 1:2

pseudocount=1e-22

inMatrix = apply(inMatrix,1:2,function(x) ifelse (x==0,pseudocount,x))

n <- 0.5 * (inMatrix[1,] + inMatrix[2,])
JS_inverse_rt5 <- 0.5 * (sum(inMatrix[1,] * log(inMatrix[1,] / n)) + sum(inMatrix[2,] * log(inMatrix[2,] / n)))
JS_inverse_rt5

JS_inverse <- sum(JS_inverse_rt1,JS_inverse_rt2,JS_inverse_rt3,JS_inverse_rt4,JS_inverse_rt5)/5
JS_inverse

JS_proportional
JS_inverse
JS_uniform
JS_unsampled
